import { createClient } from '@supabase/supabase-js';

/**
 * Promo banners: images generated by Protaige Sketch, persisted to Supabase
 * Storage (the Sketch URL is short-lived) and served on the home page for the
 * live retail-calendar event.
 */
const BUCKET = 'promo-banners';

function serviceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } }
  );
}

function publicClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? process.env.SUPABASE_ANON_KEY!,
    { auth: { persistSession: false } }
  );
}

export interface PromoBanner {
  id: string;
  event_slug: string | null;
  headline: string;
  image_url: string;
  href: string;
  locale: string;
}

const COLS = 'id, event_slug, headline, image_url, href, locale';

/** The live banner for an event (public read). */
export async function getBannerForEvent(
  eventSlug: string,
  locale = 'en'
): Promise<PromoBanner | null> {
  const { data, error } = await publicClient()
    .from('promo_banners')
    .select(COLS)
    .eq('event_slug', eventSlug)
    .eq('is_active', true)
    .in('locale', [locale, 'en'])
    .order('locale', { ascending: locale === 'en' })
    .limit(1)
    .maybeSingle();
  if (error) throw error;
  return (data as PromoBanner | null) ?? null;
}

/**
 * Download the Sketch image and store it in the public bucket, returning the
 * permanent public URL. Deterministic path per event so re-runs overwrite.
 */
export async function persistBannerImage(sketchUrl: string, key: string): Promise<string> {
  const svc = serviceClient();
  const resp = await fetch(sketchUrl);
  if (!resp.ok) throw new Error(`banner image fetch failed (${resp.status})`);
  const bytes = new Uint8Array(await resp.arrayBuffer());
  const path = `${key}.jpeg`;
  const { error } = await svc.storage
    .from(BUCKET)
    .upload(path, bytes, { contentType: 'image/jpeg', upsert: true });
  if (error) throw error;
  return svc.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;
}

/** Upsert the banner record for an event+locale (one live banner per pair). */
export async function saveBanner(input: {
  event_slug: string;
  headline: string;
  image_url: string;
  href: string;
  locale?: string;
}): Promise<void> {
  const svc = serviceClient();
  const locale = input.locale ?? 'en';
  // Retire any prior live banner for this event+locale, then insert the new one
  await svc
    .from('promo_banners')
    .update({ is_active: false })
    .eq('event_slug', input.event_slug)
    .eq('locale', locale)
    .eq('is_active', true);
  const { error } = await svc.from('promo_banners').insert({
    event_slug: input.event_slug,
    headline: input.headline,
    image_url: input.image_url,
    href: input.href,
    locale,
  });
  if (error) throw error;
}
